import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  girls: [
    {
      id: 1,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      sex: 'женский',
      height: '170 см',
      weight: '60 кг',
      chest: '3',
      age: '25л',
      nation: 'Марсианка',
      city: 'г. Москва',
      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: '1000',
      description:
        'Я профессиональная массажистка с 5-летним опытом работы. Я профессиональная массажистка с 5-летним опытом работы. Я профессиональная массажистка с 5-летним опытом работы.Я профессиональная массажистка с 5-летним опытом работы.',
      service: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 2,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      sex: 'женский',
      height: '170 см',
      weight: '60 кг',
      chest: '3',
      age: '25л',
      nation: 'Марсианка',
      city: 'г. Москва',

      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: '1000',
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      service: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 3,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      sex: 'женский',
      height: '170 см',
      weight: '60 кг',
      chest: '3',
      age: '25л',
      nation: 'Марсианка',
      city: 'г. Москва',

      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: '1000',
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      service: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 4,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      sex: 'женский',
      height: '170 см',
      weight: '60 кг',
      chest: '3',
      age: '25л',
      nation: 'Марсианка',
      city: 'г. Москва',

      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: '1000',
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      service: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 5,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      sex: 'женский',
      height: '170 см',
      weight: '60 кг',
      chest: '3',
      age: '25л',
      nation: 'Марсианка',
      city: 'г. Москва',

      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: '1000',
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      service: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 6,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      sex: 'женский',
      height: '170 см',
      weight: '60 кг',
      chest: '3',
      age: '25л',
      nation: 'Марсианка',
      city: 'г. Москва',

      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: '1000',
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      service: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 7,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      sex: 'женский',
      height: '170 см',
      weight: '60 кг',
      chest: '3',
      age: '25л',
      nation: 'Марсианка',
      city: 'г. Москва',

      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: '1000',
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      service: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 8,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      sex: 'женский',
      height: '170 см',
      weight: '60 кг',
      chest: '3',
      age: '25л',
      nation: 'Марсианка',
      city: 'г. Москва',
      address: 'г. Москва, ул. Пушкина, д. 17',
      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: '1000',
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      service: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
  ],
};

export const girlsSlice = createSlice({
  name: 'girls',
  initialState,
  reducers: {
    setGirls: (state, action) => {
      state.girls = action.payload;
    },
  },
});

export const { setGirls } = girlsSlice.actions;

export default girlsSlice.reducer;
