import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  girls: [
    {
      id: 1,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      gender: 'Женский',
      height: 175,
      weight: 55,
      chest: 3,
      age: 18,
      nation: 'Марсианка',
      city: 'г. Москва',
      address: 'г. Москва, ул. Пушкина, д. 17',
      images: ['product-1.jpg', 'product-4.jpg', 'carousel-1.jpg'],
      price: 1000,
      description:
        'Я профессиональная массажистка с 5-летним опытом работы. Я профессиональная массажистка с 5-летним опытом работы. Я профессиональная массажистка с 5-летним опытом работы.Я профессиональная массажистка с 5-летним опытом работы.',
      services: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 2,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      gender: 'Женский',
      height: 167,
      weight: 25,
      chest: 1.5,
      age: 20,
      nation: 'Марсианка',
      city: 'г. Москва',
      address: 'г. Москва, ул. Пушкина, д. 17',
      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: 3000,
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      services: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 3,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      gender: 'Женский',
      height: 168,
      weight: 49,
      chest: 2,
      age: 19,
      nation: 'Марсианка',
      city: 'г. Москва',
      address: 'г. Москва, ул. Пушкина, д. 17',
      images: ['product-4.jpg', 'product-1.jpg', 'carousel-1.jpg'],
      price: 2000,
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      services: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 4,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      gender: 'Женский',
      height: 165,
      weight: 50,
      chest: 2.5,
      age: 25,
      nation: 'Марсианка',
      city: 'г. Москва',
      address: 'г. Москва, ул. Пушкина, д. 17',
      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: 10000,
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      services: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 5,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      gender: 'Женский',
      height: 180,
      weight: 60,
      chest: 3,
      age: 22,
      nation: 'Марсианка',
      city: 'г. Москва',
      address: 'г. Москва, ул. Пушкина, д. 17',
      images: ['carousel-1.jpg', 'product-1.jpg', 'product-4.jpg'],
      price: 1400,
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      services: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 6,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      gender: 'Женский',
      height: 170,
      weight: 55,
      chest: 1,
      age: 30,
      nation: 'Марсианка',
      city: 'г. Москва',
      address: 'г. Москва, ул. Пушкина, д. 17',
      images: ['product-1.jpg', 'product-4.jpg', 'carousel-1.jpg'],
      price: 4000,
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      services: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 7,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      gender: 'Женский',
      height: 159,
      weight: 45,
      chest: 2,
      age: 24,
      nation: 'Марсианка',
      city: 'г. Москва',
      address: 'г. Москва, ул. Пушкина, д. 17',
      images: ['product-1.jpg', 'carousel-1.jpg', 'product-4.jpg'],
      price: 7000,
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      services: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
    {
      id: 8,
      name: 'Имя Фамилия',
      phone: '+7 999 999 99 99',
      reviews: ['Отличный массаж! - Иван', 'Очень доволен! - Сергей'],
      type: 'Массажистка',
      gender: 'Женский',
      height: 170,
      weight: 50,
      chest: 2.5,
      age: 19,
      nation: 'Марсианка',
      city: 'г. Москва',
      address: 'г. Москва, ул. Пушкина, д. 17',
      images: ['carousel-1.jpg', 'product-1.jpg', 'product-4.jpg'],
      price: 4000,
      description: 'Я профессиональная массажистка с 5-летним опытом работы.',
      services: ['Массаж груди', 'Массаж спины', 'Массаж пояса', 'Массаж ног'],
    },
  ],
};

export const girlsSlice = createSlice({
  name: 'girls',
  initialState,
  reducers: {
    setGirls: (state, action) => {
      state.girls = action.payload;
    },
  },
});

export const { setGirls } = girlsSlice.actions;

export default girlsSlice.reducer;
